#!/usr/bin/env bash

# Kill already running process
_ps=(mako xfce-polkit)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof "${_prs}") ]]; then
		killall -9 "${_prs}"
	fi
done

# Polkit agent
/usr/lib/xfce-polkit/xfce-polkit &

# Lauch notification daemon (mako)
~/.config/hypr/scripts/notifications &

# Launch statusbar (waybar)
waybar &

# Set cpu governor to performance
cpupower frequency-set -g performance &

# launch fcitx5
fcitx5 -d &

pkill mako


swww init

swww img ~/.config/hypr/wallpapers/76w5yo.png
